./node_modules/cordova/bin/cordova plugin add cordova-plugin-splashscreen
./node_modules/cordova/bin/cordova plugin add cordova-plugin-geolocation
./node_modules/cordova/bin/cordova plugin add cordova-plugin-dialogs
./node_modules/cordova/bin/cordova plugin add cordova-plugin-device
./node_modules/cordova/bin/cordova plugin add cordova-plugin-console
./node_modules/cordova/bin/cordova plugin add hu.dpal.phonegap.plugins.SpinnerDialog
./node_modules/cordova/bin/cordova plugin add phonegap-plugin-barcodescanner
./node_modules/cordova/bin/cordova plugin add com.clone.phonegap.plugins.pushplugin
./node_modules/cordova/bin/cordova plugin add cordova-plugin-statusbar
